export class Student {
id:number;
firstName:string;
lastName:string;
dateOfBirth:Date;
dateOfJoining:Date;
email:string;
phoneNumber:number;
password:string;
fatherName:string;
studentClass:string;
addressId:number;
houseNumber:number;
streetName:string;
city:string;
state:string;
country:string;
pincode:number;
}
